package com.example.crudspringbootdynamodb.entity;

import java.math.BigDecimal;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="ProductCatalog")
public class ProductCatalog {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;

	@DynamoDBAttribute
	private String productName;
	
	@DynamoDBAttribute
	private Integer quantity;
	
	@DynamoDBAttribute
	private Boolean inventoryLow;
	
	@DynamoDBAttribute
	private BigDecimal price;
	
	@DynamoDBAttribute
	private String currencyCode;

	public ProductCatalog() {
		
	}

	public ProductCatalog(String productName, Integer quantity, Boolean inventoryLow,
			BigDecimal price, String currencyCode) {
		this.productName = productName;
		this.quantity = quantity;
		this.inventoryLow = inventoryLow;
		this.price = price;
		this.currencyCode = currencyCode;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getProductName() {
		return productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public Integer getQuantity() {
		return quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Boolean getInventoryLow() {
		return inventoryLow;
	}

	public void setInventoryLow(Boolean inventoryLow) {
		this.inventoryLow = inventoryLow;
	}

	public BigDecimal getPrice() {
		return price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public String getCurrencyCode() {
		return currencyCode;
	}

	public void setCurrencyCode(String currencyCode) {
		this.currencyCode = currencyCode;
	}
}
